# Generated by Django 4.2.5 on 2023-09-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('burguer', '0002_produto_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='nome',
            field=models.TextField(default=''),
        ),
    ]
