# Generated by Django 4.2.5 on 2023-10-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(default='')),
                ('descricao', models.TextField()),
                ('preco', models.FloatField()),
                ('imagem', models.ImageField(default='', upload_to='cakes/img')),
            ],
        ),
    ]
